import fs from 'fs';
import path from 'path';

import { remark } from 'remark';
import html from 'remark-html';
import remarkGfm from 'remark-gfm';
import remarkBreaks from 'remark-breaks';

const BLOGS_PATH = path.join(process.cwd(), 'public', 'blogs.json');

export async function getAllBlogs(lang) {
    const file = fs.readFileSync(BLOGS_PATH, 'utf-8');
    const blogs = JSON.parse(file);
    // Convert markdown to HTML for each blog, for all languages
    const blogsWithHtml = await Promise.all(
        blogs.map(async (blog) => {
            const htmlByLang = {};
            for (const l of Object.keys(blog.content)) {
                let htmlStr = (await remark().use(remarkGfm).use(remarkBreaks).use(html).process(blog.content[l] || '')).toString();
                // Note: avoid replacing newlines in the generated HTML
                // because that can inject <br> tags inside markup (tables,
                // rows, etc.) and break elements generated by remark.
                // We keep only the adjustment that moves an existing leading
                // <br> out of an <li> so it remains visually before the list.
                htmlStr = htmlStr.replace(/<li(\b[^>]*>)\s*<br\s*\/?\s*>/g, '<br><li$1');
                htmlByLang[l] = htmlStr;
            }
            return {
                ...blog,
        slug: blog.id,
        html: htmlByLang,
    };
})
);
// If lang is specified, filter out blogs that don't have that language
  if (lang) {
    return blogsWithHtml.filter((b) => b.content[lang]);
  }
  return blogsWithHtml;
}
